### ISSUE TITLE
Phân chia công việc cho từng thành viên

### ISSUE THREAD

**Issue by phulocnguyen** [phulocnguyen/Cancer-Diagnosis-AI-based-System#2]
Ứng dụng dự kiến sẽ làm: chẩn đoán bệnh ung thư dựa trên hình ảnh
- Model: Phú Lộc + Minh Lâm
   + Đọc, nghiên cứu các tác vụ phân loại hình ảnh
  + Tìm hiểu các ứng dụng, mô hình đã có trước đây
- Front-end: Đăng Khôi + Khánh Bùi
    +Tìm hiểu xây dựng giao diện
    + Tìm thư viện + ngôn ngữ lập trình + framework phù hợp

**Comment by lamtaynha1234** [comment]
thật là cảm giác :))

okay a bắt đầu thấy hứng thú rồi đấy
